Repository nextcloud-libraries/nextcloud-typings, pull requests merged in 2023-06, with the labels that each got.

#213 chore: update workflows from templates
  .github/workflows/npm-publish.yml
Labels: dependencies, automated, 3. to review

#215 feat: Add Nextcloud 27 typings (esp. `OCP.Files.Router`)
  README.md
  lib/index.d.ts
  lib/v27/OC.d.ts
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#218 feat: add build workflow
  .github/workflows/node.yml
  package-lock.json
  package.json
  tsconfig.json
Labels: bug, dependencies
