Repository nextcloud-libraries/nextcloud-typings, pull requests merged in 2024-07, with the labels that each got.

#263 fix: Add missing types for OCP.Files.Router
  lib/v27/OC.d.ts
  lib/v28/OC.d.ts
Labels: bug, 3. to review

#265 chore: Prepare v1.9.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#267 Add SPDX header
  .github/dependabot.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/node.yml
  .github/workflows/npm-publish.yml
  .github/workflows/reuse.yml
  .gitignore
  .npmignore
  AUTHORS.md
  CHANGELOG.md
  LICENSES/CC0-1.0.txt
  LICENSES/GPL-3.0-or-later.txt
  LICENSES/MIT.txt
  README.md
  REUSE.toml
  lib/common/OC.d.ts
  lib/index.d.ts
  lib/index.ts
  lib/ocs.d.ts
  lib/v16/OC.d.ts
  lib/v17/OC.d.ts
  lib/v18/OC.d.ts
  lib/v19/OC.d.ts
  lib/v20/OC.d.ts
  lib/v21/OC.d.ts
  lib/v22/OC.d.ts
  lib/v23/OC.d.ts
  lib/v24/OC.d.ts
  lib/v25/OC.d.ts
  lib/v26/OC.d.ts
  lib/v27/OC.d.ts
  lib/v28/OC.d.ts
  lib/v29/OC.d.ts
  test/index.test.js
Labels: 3. to review

#268 Housekeeping: fix repo url and add reuse badge
  README.md
  package.json
Labels: documentation

#269 Update actions from template repo
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/node.yml
  .github/workflows/npm-publish.yml
Labels: 3. to review
